# Generated by Django 5.1.7 on 2026-04-29 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(blank=True, default='Admin', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(default='admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('task_cooldowns', models.JSONField(blank=True, default=dict)),
                ('ref_count', models.IntegerField(default=0)),
                ('ref_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=30, null=True)),
                ('welcome_bonus_given', models.BooleanField(default=False)),
                ('flash_bonus_last_claimed', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('role', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('earning', 'Earning'), ('bonus', 'Bonus'), ('referral', 'Referral'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('referred_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=200, null=True)),
                ('network_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ngn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deduction_pending', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.userprofile')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ngn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=200, null=True)),
                ('network_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='api.userprofile')),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-timestamp'],
            },
        ),
    ]
