# Generated by Django 5.1.9 on 2026-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='receipt_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
